export const LOCATION_CHANGE = 'LOCATION_CHANGE'
export const LOCATION_FOCUS = 'LOCATION_FOCUS'

export const WEATHER_GET_REQUEST = 'WEATHER_GET_REQUEST'
export const WEATHER_GET_RESPONSE = 'WEATHER_GET_RESPONSE'
export const WEATHER_GET_ERROR = 'WEATHER_GET_ERROR'

export const WEATHER_SELECT_DAY = 'WEATHER_SELECT_DAY'